steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia.gcr.io/steel-fin-459711-k9/capstone-server:$SHORT_SHA
      - -f
      - code/node/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia.gcr.io/steel-fin-459711-k9/capstone-server:$SHORT_SHA
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/capstone-express
      - capstone-server=asia.gcr.io/steel-fin-459711-k9/capstone-server:$SHORT_SHA
    env:
      - CLOUDSDK_COMPUTE_REGION=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1

images:
  - asia.gcr.io/steel-fin-459711-k9/capstone-server:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
