steps:
  #############################################
  # 1. GCP 서비스 계정 키 Secret 생성
  #############################################
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔐 Creating Kubernetes Secret for GCP key..."

        # 기존 secret 삭제
        kubectl delete secret capstone-secrets --ignore-not-found

        # Secret 생성
        kubectl create secret generic capstone-secrets \
          --from-literal=GCP_SA_KEY_BASE64="${_GCP_SA_KEY}" \
          --from-literal=GOOGLE_CLOUD_STORAGE_BUCKET="steel-fin-459711-k9-01424cceaf04" \
          --from-literal=GOOGLE_CLOUD_PROJECT_ID="steel-fin-459711-k9" \
          --from-literal=KAKAO_API_KEY="1e1e4cdde8201f18aacae19257f3fffa"
    env:
      - CLOUDSDK_COMPUTE_REGION=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1
      - _GCP_SA_KEY=${_GCP_SA_KEY}

  #############################################
  # 2. Express (Node.js 서버) 빌드 및 배포
  #############################################
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia.gcr.io/steel-fin-459711-k9/capstone-server:$SHORT_SHA
      - -f
      - code/node/Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia.gcr.io/steel-fin-459711-k9/capstone-server:$SHORT_SHA

  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/capstone-express
      - capstone-server-sha256-1=asia.gcr.io/steel-fin-459711-k9/capstone-server:$SHORT_SHA
    env:
      - CLOUDSDK_COMPUTE_REGION=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1

  #############################################
  # 3. Flask (Python AI 서버) 빌드 및 배포
  #############################################
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia.gcr.io/steel-fin-459711-k9/capstone-flask:$SHORT_SHA
      - -f
      - code/python/Dockerfile
      - code/python

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia.gcr.io/steel-fin-459711-k9/capstone-flask:$SHORT_SHA

  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/capstone-ai
      - flask-ai-server-sha256-1=asia.gcr.io/steel-fin-459711-k9/capstone-flask:$SHORT_SHA
    env:
      - CLOUDSDK_COMPUTE_REGION=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=
