options:
  logging: CLOUD_LOGGING_ONLY  # 로그는 GCP Cloud Logging으로만 기록

steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - code/node/docker-compose.k8s.prod.yaml
      - build

  - name: docker/compose:1.29.0
    args:
      - -f
      - code/node/docker-compose.k8s.prod.yaml
      - push

  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/capstone-nestjs
      - capstone-nestjs=asia.gcr.io/steel-fin-459711-k9/capstone-mysql:0.1
    env:
      - CLOUDSDK_COMPUTE_REGION=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1
